version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=nima
      - POSTGRES_USER=root2
      - POSTGRES_PASSWORD=123123
  web:
    build:
      context: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
